logging:
    config: classpath:logback.xml
xxl:
    job:
        accessToken: ''
        admin:
            addresses: http://192.168.5.128:8093/xxl-job-admin/ # 服务器的可视化x-job admin的地址
        executor:
            address: ''
            appname: xxl-stock-executor # 定义执行器应用名称
            ip: ''
            logpath: ./logs
            logretentiondays: 30
            port: 7979 # 指定任务工程与admin工程心跳检查端口
